/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Administracion_Supermercado;

import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class Dlg_Congelado extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dlg_Congelado.class.getName());

    /**
     * Creates new form Dlg_Conge
     */
    public Dlg_Congelado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblNombre = new javax.swing.JLabel();
        lblCaduc = new javax.swing.JLabel();
        lbl_Lote = new javax.swing.JLabel();
        lblConge = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDatos = new javax.swing.JTextArea();
        jtCongela = new javax.swing.JTextField();
        jtNom = new javax.swing.JTextField();
        jtFecha = new javax.swing.JTextField();
        jtLote = new javax.swing.JTextField();
        btnImpri = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        btnSal = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        lblCaduc.setText("Fecha de Caducidad:");
        getContentPane().add(lblCaduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lbl_Lote.setText("Numero de Lote:");
        getContentPane().add(lbl_Lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        lblConge.setText("Temperatura de Congelacion:");
        getContentPane().add(lblConge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jtaDatos.setColumns(20);
        jtaDatos.setRows(5);
        jScrollPane1.setViewportView(jtaDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 230, 200));

        jtCongela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCongelaActionPerformed(evt);
            }
        });
        getContentPane().add(jtCongela, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, -1));

        jtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomActionPerformed(evt);
            }
        });
        getContentPane().add(jtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 100, -1));
        getContentPane().add(jtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));
        getContentPane().add(jtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, -1));

        btnImpri.setText("Imprimir");
        btnImpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpriActionPerformed(evt);
            }
        });
        getContentPane().add(btnImpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnLim.setText("Limpiar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });
        getContentPane().add(btnLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        btnSal.setText("Salir");
        btnSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalActionPerformed(evt);
            }
        });
        getContentPane().add(btnSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        setSize(new java.awt.Dimension(648, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomActionPerformed

    }//GEN-LAST:event_jtNomActionPerformed

    private void btnImpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpriActionPerformed

        try {
            int lote = Integer.parseInt(jtLote.getText());
            double temperatura = Double.parseDouble(jtCongela.getText());

            Producto_Congelado congelado = new Producto_Congelado(
                    jtNom.getText(),
                    jtFecha.getText(),
                    lote,
                    temperatura
            );

            jtaDatos.setText(congelado.mostrarInfo());

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, ";) Es un error sabes? el Lote y Temperatura deben ser numericos. ");

        }
    }//GEN-LAST:event_btnImpriActionPerformed

    private void btnSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        jtNom.setText("");
        jtFecha.setText("");
        jtLote.setText("");
        jtCongela.setText("");
        jtaDatos.setText("");    
    }//GEN-LAST:event_btnLimActionPerformed

    private void jtCongelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCongelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCongelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dlg_Congelado dialog = new Dlg_Congelado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImpri;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton btnSal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtCongela;
    private javax.swing.JTextField jtFecha;
    private javax.swing.JTextField jtLote;
    private javax.swing.JTextField jtNom;
    private javax.swing.JTextArea jtaDatos;
    private javax.swing.JLabel lblCaduc;
    private javax.swing.JLabel lblConge;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbl_Lote;
    // End of variables declaration//GEN-END:variables
}
