/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Administracion_Supermercado;

import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class Dlg_Fresco extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dlg_Fresco.class.getName());

    /**
     * Creates new form Dlg_Congelado
     */
    public Dlg_Fresco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNom = new javax.swing.JLabel();
        jtNom = new javax.swing.JTextField();
        lblCadu = new javax.swing.JLabel();
        lblLote = new javax.swing.JLabel();
        jtCaduc = new javax.swing.JTextField();
        jtLot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();
        btnImpri = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        btnSal = new javax.swing.JButton();
        lblEnva = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        jtEnva = new javax.swing.JTextField();
        jtOrigen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto Fresco");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNom.setText("Nombre");
        getContentPane().add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));
        getContentPane().add(jtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, -1));

        lblCadu.setText("Fecha de Caducidad");
        getContentPane().add(lblCadu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblLote.setText("Numero de Lote");
        getContentPane().add(lblLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(jtCaduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));
        getContentPane().add(jtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));

        txaMostrar.setColumns(20);
        txaMostrar.setRows(5);
        jScrollPane1.setViewportView(txaMostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 220, 190));

        btnImpri.setText("Imprimir");
        btnImpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpriActionPerformed(evt);
            }
        });
        getContentPane().add(btnImpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 30));

        btnLim.setText("Limpiar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });
        getContentPane().add(btnLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 90, 30));

        btnSal.setText("Salir");
        btnSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalActionPerformed(evt);
            }
        });
        getContentPane().add(btnSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 80, 30));

        lblEnva.setText("Fecha de Envasado");
        getContentPane().add(lblEnva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblOrigen.setText("Pais de Origen");
        getContentPane().add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jtEnva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEnvaActionPerformed(evt);
            }
        });
        getContentPane().add(jtEnva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));

        jtOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(jtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, -1));

        setSize(new java.awt.Dimension(618, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpriActionPerformed
        try {

            int lote = Integer.parseInt(jtLot.getText());

            Producto_Fresco fresco = new Producto_Fresco(
                    jtNom.getText(),
                    jtCaduc.getText(),
                    lote,
                    jtEnva.getText(),
                    jtOrigen.getText()
            );

            txaMostrar.setText(fresco.mostrarInfo());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, ";) Es un error sabes? el Lote debe ser numerico.");
        }
    }//GEN-LAST:event_btnImpriActionPerformed

    private void jtEnvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEnvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEnvaActionPerformed

    private void jtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtOrigenActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        jtNom.setText("");
        jtCaduc.setText("");
        jtLot.setText("");
        jtEnva.setText("");
        jtOrigen.setText("");
        txaMostrar.setText("");

    }//GEN-LAST:event_btnLimActionPerformed

    private void btnSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dlg_Fresco dialog = new Dlg_Fresco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImpri;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton btnSal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtCaduc;
    private javax.swing.JTextField jtEnva;
    private javax.swing.JTextField jtLot;
    private javax.swing.JTextField jtNom;
    private javax.swing.JTextField jtOrigen;
    private javax.swing.JLabel lblCadu;
    private javax.swing.JLabel lblEnva;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JTextArea txaMostrar;
    // End of variables declaration//GEN-END:variables
}
