/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Administracion_Supermercado;

import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class Dlg_Refrigerado extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dlg_Refrigerado.class.getName());

    /**
     * Creates new form Dlg_Refrigerado
     */
    public Dlg_Refrigerado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblCaduc = new javax.swing.JLabel();
        lblLote = new javax.swing.JLabel();
        lbl_Codigo = new javax.swing.JLabel();
        btnImpri = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMostrar = new javax.swing.JTextArea();
        jtNom = new javax.swing.JTextField();
        jtCaduc = new javax.swing.JTextField();
        jtLot = new javax.swing.JTextField();
        jtOrga = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto Refrigerado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lblCaduc.setText("Caducidad:");
        getContentPane().add(lblCaduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        lblLote.setText("Lote:");
        getContentPane().add(lblLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        lbl_Codigo.setText("Codigo de Organismo:");
        getContentPane().add(lbl_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnImpri.setText("Imprimir");
        btnImpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpriActionPerformed(evt);
            }
        });
        getContentPane().add(btnImpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        btnLim.setText("Limpiar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });
        getContentPane().add(btnLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jtaMostrar.setColumns(20);
        jtaMostrar.setRows(5);
        jScrollPane1.setViewportView(jtaMostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 240, 170));
        getContentPane().add(jtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 90, -1));
        getContentPane().add(jtCaduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 90, -1));
        getContentPane().add(jtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 90, -1));
        getContentPane().add(jtOrga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 90, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        setSize(new java.awt.Dimension(608, 319));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpriActionPerformed
        try {

            int lote = Integer.parseInt(jtLot.getText());

            Producto_Refrigerado refrigerado = new Producto_Refrigerado(
                    jtNom.getText(),
                    jtCaduc.getText(),
                    lote,
                    jtOrga.getText()
            );

            jtaMostrar.setText(refrigerado.mostrarInfo());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, " ;) Es un error sabes? el Lote debe ser numerico.");
        }


    }//GEN-LAST:event_btnImpriActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        jtNom.setText("");
        jtCaduc.setText("");
        jtLot.setText("");
        jtOrga.setText("");
        jtaMostrar.setText("");
    }//GEN-LAST:event_btnLimActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dlg_Refrigerado dialog = new Dlg_Refrigerado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImpri;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtCaduc;
    private javax.swing.JTextField jtLot;
    private javax.swing.JTextField jtNom;
    private javax.swing.JTextField jtOrga;
    private javax.swing.JTextArea jtaMostrar;
    private javax.swing.JLabel lblCaduc;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbl_Codigo;
    // End of variables declaration//GEN-END:variables
}
