/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administracion_Supermercado;

import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class Frm_Supermercado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frm_Supermercado.class.getName());

    /**
     * Creates new form Frm_Supermercado
     */
    public Frm_Supermercado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCongelado = new javax.swing.JMenuItem();
        jmFresco = new javax.swing.JMenuItem();
        jmRefri = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado \"Todos Ganan\"");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jMenu1.setText("Productos");

        jmCongelado.setText("Producto Congelado");
        jmCongelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCongeladoActionPerformed(evt);
            }
        });
        jMenu1.add(jmCongelado);

        jmFresco.setText("Producto Fresco");
        jmFresco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFrescoActionPerformed(evt);
            }
        });
        jMenu1.add(jmFresco);

        jmRefri.setText("Producto Refrigerado");
        jmRefri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRefriActionPerformed(evt);
            }
        });
        jMenu1.add(jmRefri);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(435, 263));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jmRefriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRefriActionPerformed
     Dlg_Refrigerado dlg = new Dlg_Refrigerado(this, true);
     dlg.setVisible(true);   
    }//GEN-LAST:event_jmRefriActionPerformed

    private void jmCongeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCongeladoActionPerformed
        Dlg_Congelado dlg = new Dlg_Congelado(this, true);
        dlg.setVisible(true);   
    }//GEN-LAST:event_jmCongeladoActionPerformed

    
    private void jmFrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFrescoActionPerformed
     Dlg_Fresco dlg = new Dlg_Fresco(this, true);
     dlg.setVisible(true);
        
        
    }//GEN-LAST:event_jmFrescoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int rpta = JOptionPane.showOptionDialog(this,
                "Estas seguro de salir?", "Mensaje de Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, null, null);
        if (rpta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frm_Supermercado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmCongelado;
    private javax.swing.JMenuItem jmFresco;
    private javax.swing.JMenuItem jmRefri;
    // End of variables declaration//GEN-END:variables
}
